name: Verdaccio Website CI

on:
  workflow_dispatch:
  pull_request:
    paths:
        - 'website/**'
        - './.github/workflows/website.yml'
  schedule:
    - cron: '0 0 * * *' 

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    permissions:
      contents: read  #  to fetch code (actions/checkout)
      deployments: write
      pull-requests: write  #  to comment on pull-requests

    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
        env:
          NODE_ENV: production    
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: |
          corepack enable
          corepack install
      - name: set store
        run: |
          mkdir ~/.pnpm-store
          pnpm config set store-dir ~/.pnpm-store
      - name: Install
        run: pnpm install  --registry http://localhost:4873
      - name: Cache .pnpm-store
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-          
      - name: Build 
        run: pnpm build
      - name: Build Translations percentage
        run: pnpm --filter @verdaccio/crowdin-translations build
      - name: Cache Docusaurus Build
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: website/node_modules/.cache/webpack
          key: cache/webpack-${{github.ref}}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: cache/webpack-${{github.ref}}

      # Will deploy to production on:
        # 1st: When a push occurs on master branch
        # 2nd: When we force the worflow dispatch through the UI
      - name: Build Production
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        env:
          CROWDIN_VERDACCIO_API_KEY: ${{ secrets.CROWDIN_VERDACCIO_API_KEY }}
          SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
          CONTEXT: production
        run: pnpm --filter @verdaccio/website netlify:build:production

      - name: 🔥 Deploy Production Netlify
        if: (github.event_name == 'push' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        uses: verdaccio/action-netlify-deploy@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './website/build'

      # Will deploy to Preview URL, only when a pull request is open with changes on the website
      - name: Build Deployment Preview
        env:
          CONTEXT: deploy-preview
        run: pnpm --filter ...@verdaccio/website netlify:build:deployPreview

      - name: 🤖 Deploy Preview Netlify
        if: github.repository == 'verdaccio/verdaccio'
        uses: verdaccio/action-netlify-deploy@master
        id: netlify_preview
        with:
          draft: true
          comment-on-pull-request: true
          github-deployment-is-production: false
          github-deployment-is-transient: true
          configPath: './netlify.toml' 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './website/build'
